### ISSUE TITLE
minimap with player FOV

### ISSUE THREAD

**Issue by sheydz** [sheydz/CmdFPS#1]
should show the minimap with the area the player can see similar to cs or other FPS games:

![Image](https://user-images.githubusercontent.com/93658810/201473178-a449018b-55a3-4247-b97c-e18030dd78e0.png)

**Comment by philip-seitz** [comment]
Has been implemented in slightly different way. The triangular shape of the radar looked a bit off when moving and turning so I just went with a straight pointing in the direction of the player angle:
![grafik](https://user-images.githubusercontent.com/93658810/208771960-3906c4d9-ece1-4d8d-981c-27fbc75802de.png)
